github:
  repo_owner: "ReadMediaApp"
  repo_name: "ReadMediaApp.github.io"
  branch: "main"
  token: ""  # Not needed for static deployment

paths:
  frontend_dir: "./"      # For root deployment
  upload_dir: "./uploads"

content:
  allowed_extensions:
    books: [".pdf", ".epub", ".mobi"]
    images: [".jpg", ".jpeg", ".png", ".gif", ".webp"]
  max_file_size: 50MB

affiliate:
  allowed_domains:
    - "amazon.com"
    - "amazon.co.uk"
    - "goodreads.com"
    - "bookshop.org"
    - "amzn.to"